version: '3.8'

services:
  noteapp:
    image: ganeshvenkatasai/noteapp:latest
    container_name: noteapp_backend
    restart: always
    environment:
      DATABASE_URL: 'postgres://avnadmin:AVNS_wrkNseB_iSwng4azMWD@noteappdb-zoinme.k.aivencloud.com:22802/defaultdb?sslmode=require'
    ports:
      - "7000:7000"
    networks:
      - noteapp_network

  client:
    image: ganeshvenkatasai/client:latest
    container_name: noteapp_client
    restart: always
    environment:
      REACT_APP_API_BASE_URL: "http://noteapp:7000"
      REACT_APP_GOOGLE_CLIENT_ID: "437083640575-eqgncvtn6ham29h67rskg8ibaku1jva8.apps.googleusercontent.com"
    ports:
      - "3000:80"  
    depends_on:
      - noteapp
    networks:
      - noteapp_network

networks:
  noteapp_network:
    driver: bridge
