apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}"
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
        env:
        - name: DATABASE_URL
          value: "{{ .Values.backend.env.DATABASE_URL }}"
