apiVersion: v1
kind: Service
metadata:
  name: noteapp
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.backendPort }}
      targetPort: {{ .Values.backend.containerPort }}
  type: {{ .Values.service.type }}
