apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.frontend.containerPort }}
  type: {{ .Values.service.type }}
